# -*- coding: utf-8 -*-

# Dialog implementation generated from reading ui file 'affichagepartelephone.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import  QTableWidget, QTableWidgetItem 
from PyQt5.QtWidgets import QApplication,QLineEdit, QTextEdit

class Ui_Form(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setMinimumSize(QtCore.QSize(800, 600))
        Dialog.setMaximumSize(QtCore.QSize(800, 600))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, -5, 801, 611))
        self.label.setStyleSheet("background-image: url(:/newPrefix/mer800-600.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        """self.texttel = QtWidgets.QTextEdit(Dialog)
        self.texttel.setGeometry(QtCore.QRect(30, 400, 721, 171))
        self.texttel.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.texttel.setObjectName("texttel")"""
        #table
        self.table = QTableWidget(Dialog)
        self.table.setGeometry(10 , 400 , 780, 110)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(110, 20, 500, 31))
        self.label_2.setStyleSheet("font: 8pt \"Nirmala UI\";\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"\n"
"")
        
        self.Buttonrech = QtWidgets.QPushButton(Dialog)
        self.Buttonrech.setGeometry(QtCore.QRect(300, 310, 190, 31))
        self.Buttonrech.setObjectName("Buttonrech")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(200, 30, 550, 81))
        self.label_2.setStyleSheet("font: 8pt \"Nirmala UI\";\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.linetel = QtWidgets.QLineEdit(Dialog)
        self.linetel.setGeometry(QtCore.QRect(410, 200, 211, 31))
        self.linetel.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.linetel.setObjectName("linetel")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(100, 190, 300, 41))
        self.label_3.setStyleSheet("font: 8pt \"Nirmala UI\";\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Recherche par Numéro de téléphone"))
        self.Buttonrech.setText(_translate("Dialog", "recherche et affichage"))
        self.label_2.setText(_translate("Dialog", "Recherche par téléphone"))
        self.label_3.setText(_translate("Dialog", "Numéro de téléphone :"))
    
    def getbouttonrechafftel(self):
        return self.Buttonrech
    def getTable(self):
        return self.table


from photo import photos2


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QWidget()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
