# -*- coding: utf-8 -*-

# Dialog implementation generated from reading ui file 'affichageparmaladies.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import  QTableWidget, QTableWidgetItem



class Ui_Form(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setMinimumSize(QtCore.QSize(800, 600))
        Dialog.setMaximumSize(QtCore.QSize(800, 600))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.label.setStyleSheet("background-image: url(:/newPrefix/mer800-600.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        """self.textmal = QtWidgets.QTextEdit(Dialog)
        self.textmal.setGeometry(QtCore.QRect(40, 350, 721, 231))
        self.textmal.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.textmal.setObjectName("textmal")"""
        
        #table
        self.table = QTableWidget(Dialog)
        self.table.setGeometry(10 , 330 , 780 , 256)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(110, 20, 500, 31))
        self.label_5.setStyleSheet("font: 8pt \"Nirmala UI\";\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"\n"
"")
        
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(270, 30, 380, 71))
        self.label_2.setStyleSheet("font: 8pt \"Nirmala UI\";\n"
"font: 16pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(170, 170, 151, 41))
        self.label_3.setStyleSheet("font: 8pt \"Nirmala UI\";\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.Buttonrech = QtWidgets.QPushButton(Dialog)
        self.Buttonrech.setGeometry(QtCore.QRect(250, 270, 320, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Buttonrech.setFont(font)
        self.Buttonrech.setObjectName("Buttonrech")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(330, 170, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        
        

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Recherche par une maladie"))
        self.label_2.setText(_translate("Dialog", "Recherche par maladies"))
        self.label_3.setText(_translate("Dialog", "Maladie :"))
        self.Buttonrech.setText(_translate("Dialog", "recherche et affichage"))
        self.comboBox.setItemText(1, _translate("Dialog", "ASTHME"))
        self.comboBox.setItemText(2, _translate("Dialog", "DIABETE"))
        self.comboBox.setItemText(3, _translate("Dialog", "HYPERTENSION"))
    
    def getTable(self):
        return self.table
        
    def getbouttonaffichageparmaladie(self):
        return self.Buttonrech
        
from photo import photos2


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QWidget()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
